#db related settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:4321/notedb
    username: jhin
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: NoteService
  cloud:
    discovery:
      enabled: true


#eureka client setting
eureka:
  instance:
    hostname: localhost
server:
  port: 8081


#actuator settings

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
info:
  app:
    name: "This Jhin's note service"
    version: "1.0.0"
    description: "Note service and assigned workers for tis tasks"


