#db related settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:4321/notedb
    username: jhin
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: NoteService
  cloud:
    discovery:
      enabled: true


#eureka client setting
eureka:
  instance:
    hostname: localhost
server:
  port: 8081


